[window]
padding = { x = 15, y = 15 }
opacity = 0.85
decorations = "None"
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 11.0

[colors]
draw_bold_text_with_bright_colors = true